# Generated by Django 5.2.7 on 2025-12-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_used_trial',
            field=models.BooleanField(default=False, help_text='Whether the user has used their free trial'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('subscriber', 'Subscriber')], default='subscriber', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='trial_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the free trial expires', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, help_text='When the free trial started', null=True),
        ),
    ]
