# Generated by Django 5.2.7 on 2025-12-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_has_used_trial_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('subscriber', 'Subscriber'), ('normal', 'Normal')], default='normal', max_length=20),
        ),
    ]
